#!/bin/bash

# Set the desired mode
mode="-rwxr-x-wx"

# Set the owner and group
owner="julien"
group="julien"

# Set the timestamp
timestamp="Sep 20 14:25"

# Set the file name
filename="hello"

# Set the permissions
permissions=$(echo "$mode" | sed 's/./& /g')

# Set the command
command="chmod ${permissions} \"$filename\""

# Execute the command
eval "$command"

# Set the owner and group
chown "$owner:$group" "$filename"

# Set the timestamp
touch -d "$timestamp" "$filename"
